// Simple HTTP requests for testing Chirpy Bootdev service - I used this with VSCode REST Client extension

# http://localhost:8080/admin/metrics

POST http://localhost:8080/api/123 HTTP/1.1
content-type: application/json

{
    "body": "chirp content"
}
